### ISSUE TITLE
AssemblyResolutionException when publicizing internals on .Net Framework 4.6

### ISSUE THREAD

**Issue by svick** [aelij/IgnoresAccessChecksToGenerator#4]
1. Create a new .Net Framework 4.6 class library in Visual Studio.
2. Install the IgnoresAccessChecksToGenerator NuGet package (select the PackageReference package manager format)
3. Install the Microsoft.CodeAnalysis.Common package.
4. Add the following to the csproj in an external editor:

    ```xml
    <PropertyGroup>
      <InternalsAssemblyNames>Microsoft.CodeAnalysis</InternalsAssemblyNames>
    </PropertyGroup>
    ```
5. Reload the Project as prompted by VS.
6. Build solution.

This produces the error:

```
Error		The "PublicizeInternals" task failed unexpectedly.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at IgnoresAccessChecksToGenerator.Tasks.PublicizeInternals.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at IgnoresAccessChecksToGenerator.Tasks.PublicizeInternals.AssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at IgnoresAccessChecksToGenerator.Tasks.PublicizeInternals.CreatePublicAssembly(String source, String target)
   at IgnoresAccessChecksToGenerator.Tasks.PublicizeInternals.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

If I change the target framework to .Net Framework 4.7.2 and build again, the build succeeds.

**Comment by sailro** [comment]
This is probably because your target assembly is using .NET Standard.

I had the same issue with a .NET 4.6 project, as a workaround:

Add the two following packages to your packages.config:

```
<package id="System.Runtime" version="4.0.0" targetFramework="net46" developmentDependency="true" />  
<package id="System.Reflection.Metadata" version="1.2.0" targetFramework="net46" developmentDependency="true" />
```
Then add references to them in your csproj:
```
<Reference Include="System.Runtime">
  <HintPath>..\packages\System.Runtime.4.0.0\ref\dotnet\System.Runtime.dll</HintPath>
  <Private>False</Private>
</Reference>	
<Reference Include="System.Reflection.Metadata">
  <HintPath>..\packages\System.Reflection.Metadata.1.2.0\lib\portable-net45+win8\System.Reflection.Metadata.dll</HintPath>
  <Private>False</Private>
</Reference>	
```

The IgnoresAccessChecksToGenerator build target will now then be able to properly resolve assemblies.

**Comment by aelij** [comment]
Closing as 4.6 is out of support anyhow
